CREATE TABLE customers
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name          VARCHAR(256)        NOT NULL,
    last_name           VARCHAR(256)        NOT NULL,
    email               VARCHAR(256) UNIQUE NOT NULL,
    verification_status VARCHAR(50)
);